### PR TITLE
Add SocksClient enabled http.Agent 

### PR DESCRIPTION
**Pull request by gordalina**

### CODE REVIEW

**Comment by JoshGlazebrook** [comment]
Looking good. Sorry I've been busy! I'll test it out this afternoon.

**Comment by JoshGlazebrook** [comment]
Do you think it would be better to have the main function in SocksAgent to be createConnection() rather than createSocksConnection() to have uniformity between the two main exports?

**Comment by gordalina** [comment]
I've updated it to be named `createConnection`. 
It is not really required, because you don't call it directly.

**Comment by JoshGlazebrook** [comment]
I think I was half asleep when I wrote that comment. That really didn't matter at all. lol

Do you know the process of trying to take over an abandoned (development wise) npm module? I've tried contacting the owner of the "socks" module and they have not responded. 

I did read though:

https://www.npmjs.com/policies/disputes

And I did CC my email to the support npm email address but haven't heard back. Probably is just a lost cause but who knows. Would be nice to have the socks name but socks-client is an appropriate name for this anyways.

**Comment by gordalina** [comment]
I never had that issue before, but `socks-client` is the best candidate to be called socks.
It supports socks4,5 and with this pull request can be used as an agent.
The only thing lacking is a socks server (to really be called socks)

**Comment by gordalina** [comment]
Anyway, is this a blocker for this PR? Maybe it could be merged and tagged/released a new version.

**Comment by JoshGlazebrook** [comment]
Should be good to go on NPM.

**Comment by gordalina** [comment]
perfect, thanks

**Pull request merged**
